### ISSUE TITLE
Updating of only the root A record

### ISSUE THREAD

**Issue by M7rc7ry** [CyrusKao/cf-ddns-cli#1]
When i use your script to update only example.com it returns multiple records found. How do we use it to update only the root A record ?

**Comment by CyrusKao** [comment]
It means there are preexisting records (which are not managed by cf-ddns) on that name. For safety reasons, you'll have to remove them manually before using cf-ddns.

**Comment by M7rc7ry** [comment]
Hi. This turned out to be the perfect solution for you program to update the root record. By creating a root CNAME record pointing to a subdomain A record of "dynamic.example.com" i was able to update the dynamic.example.com record straight away.
![image](https://user-images.githubusercontent.com/11647905/195987817-e2664c9a-6e62-441f-b2bb-4b0a75a22a0b.png)
